### ISSUE TITLE
如果我想适配横屏拍摄需要如何处理呢？

### ISSUE THREAD

**Issue by tanghubin** [lihangleo2/MyCamera#1]
如果我想适配横屏拍摄需要如何处理呢？比如，我想横着拍的时候，播放的时候 也是横屏视频，这样子。

**Comment by lihangleo2** [comment]
如果想固定成横屏，在Androidmanifest里修改screenOrientation属性。如果是想横竖切换，那你还要利用onSaveInstanceState做数据存储和恢复

唐扈彬 <notifications@github.com> 于2020年4月14日周二 下午6:56写道：
